# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['-price', 'name'], 'verbose_name': 'Item', 'verbose_name_plural': 'items'},
        ),
        migrations.AddField(
            model_name='good',
            name='price',
            field=models.IntegerField(default=10, unique=True, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Category'),
        ),
        migrations.AlterField(
            model_name='good',
            name='in_stock',
            field=models.BooleanField(db_index=True, default=True, verbose_name='In Stock'),
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='good',
            unique_together=set([('category', 'name', 'price')]),
        ),
    ]
