# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_good_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='description',
        ),
    ]
