# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_remove_good_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
