# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_good_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
