# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Title'),
        ),
    ]
