# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_auto_20170326_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='pub_date'),
        ),
    ]
